### ISSUE TITLE
xpath rules doesn't work in sonarqube 7.6 or 7.9[question]

### ISSUE THREAD

**Issue by xsser** [jborgers/sonar-pmd#175]
sonarqube version:`7.6&7.9`
xpath I wrote : `//Name`
sonar-pmd-plugin version:`3.2.0&& 3.2.1`

Both of them don't work  
Is there a version that is compatible with sonarqube 7.9?
Thanks in advance

**Comment by kinbod** [comment]
7.9 would adapt in future?

**Comment by xsser** [comment]
> 7.9 would adapt in future?
I quited ,lol  
CodeQL instead

**Comment by jborgers** [comment]
It should work in Sonar 8.9/9.4 with the release 3.4.0.
