### ISSUE TITLE
pmd:LawOfDemeter

### ISSUE THREAD

**Issue by amedee** [jborgers/sonar-pmd#182]
From https://community.sonarsource.com/t/pmd-lawofdemeter/27359

which versions are you using (SonarQube: Developer Edition Version 7.7 (build 23042), Scanner: mvn sonar:sonar, Plugin: PMD 3.2.1, and any relevant extension: SonarJava 5.13.1 (build 18282))
what are you trying to achieve: write high quality software
what have you tried so far to achieve this: activate pmd rules in Quality Profile and run SonarQube analysis
Copy/paste from Jira issue written by a developer (I have not verified):

Disable pmd:LawOfDemeter check from SonarQube

There are a ton of false positive reports for that tool. Example is on the screenshot:

1223×437 27.8 KB
Another example for the Java API (Pattern and Matches classes) that it complains about:

1115×170 11.8 KB
After the discussion within the team I haven’t heard of any true positive and helpful report of that rule but I’ve heard about a ton of false positive ones (e.g. from Lera or Yauheni) which were cross-confirmed as such by Yulian. Thus, this check should be disabled.

My reply to the developer:

So what you are saying is, there are too many false positives, when using .equals() and .matches()?
I’d say that’s an excellent case to submit as a bug report to the authors of the plugin. I’m on it!

So here I am…

G Ann Campbell
ganncamp
SonarSourcer
1d
Hi,

Thanks for the report. Unfortunately, it’s slightly mis-directed. You should file an issue on the PMD project.

 
:smiley:
Ann

**Comment by mohanaraosv** [comment]
@amedee As Ann commented above you have to report this issue in https://github.com/pmd/pmd/issues sonar-pmd is a wrapper but the actual issue lies on PMD itself.

**Comment by jborgers** [comment]
Seems we can close this issue
