### ISSUE TITLE
Investigate ignored rules

### ISSUE THREAD

**Issue by timwebster9** [jborgers/sonar-pmd#21]
See https://groups.google.com/d/msg/sonarqube/6rmOvVAlsj4/lBkskDkUBQAJ

**Comment by timwebster9** [comment]
The ignored rule is 'Xpath rule template'.  It is deliberately excluded from importing into a quality profile.  From PmdProfileImporter.java:

 if (PmdConstants.XPATH_CLASS.equals(ruleClassName)) {
        messages.addWarningText("PMD XPath rule '" + pmdRule.getName()
          + "' can't be imported automatically. The rule must be created manually through the SonarQube web interface.");
      } 

The rule documentation states that the rule is deprecated, and provides a link to show how to create custom XPath rules using in the native SonarQube manner, however the link is broken.

Probably best to just remove this rule?

**Comment by timwebster9** [comment]
on second thought to preserve backwards compatibility this needs to stay in...

**Comment by jborgers** [comment]
Can we close this issue?

**Comment by jborgers** [comment]
Old version. Assuming not relevant anymore.
