### ISSUE TITLE
Meet error Unsupported Java version for PMD: 14 when run sonar scan with SonarQube-7.9.4

### ISSUE THREAD

**Issue by yogesh206145** [jborgers/sonar-pmd#242]
Hi,
We are using Java 14 in our source, but we met below error when run Sonar Scan with sonarqube 7.9.4. It looks like the PMD plugin doesn't support java 14. I am using sonarPMD 3.2.1 in the server.  I can see support for  3.3.x with java 15 in plugin matrix. Please suggest which version of plugin I have to use in SonarQube 7.9.4(LTS) to get the benefit on java 14. I cant find 3.3.x plugins. Is it tested on SonarQube 7.9.4 LTS ?

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project aid-range-ocean: Unsupported Java version for PMD: 14 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionExceptio

**Comment by mohanaraosv** [comment]
I believe it will be covered in [Milestone 3.3](https://github.com/jensgerdes/sonar-pmd/milestone/3?closed=1) so far it is in progress, I do believe supports Java 14 as well.

**Comment by jensgerdes** [comment]
Hi @yogesh206145 

Thank you for your report. Yes, @mohanaraosv is right - this has been fixed in the current release *3.3.0*.
You can try out the new release by downloading it from [here](https://github.com/jensgerdes/sonar-pmd/releases/tag/3.3.0) and replacing the existing sonar-pmd-plugin-3.2.1.jar with this one in your SonarQube plugins directory.

Alternatively, you can wait for the release in the Sonar market place which usually takes some time.

**Comment by yogesh206145** [comment]
hi @jensgerdes !
Thank you very much for your support. Is it tested properly with 7.9.4 LTS so that I can apply this plugin in our production instance ?
Kr,
Yogesh

**Comment by jensgerdes** [comment]
It has been tested on 7.9.5 LTS in several scenarios. See: https://travis-ci.org/github/jensgerdes/sonar-pmd/jobs/754023316
Nonetheless, it has not yet been beta-tested by the community - so try it with care.

It has been tested along with the latest Sonar-Java version available in the Sonarmarket place. I assume you'll have a recent version of it running.

**Comment by yogesh206145** [comment]
Thank you very much. I have 7.9.4 LTS with all latest supported plugins.
Kr,
Yogesh

**Comment by jborgers** [comment]
It seems this is solved.
