### ISSUE TITLE
Add support for JDK 17

### ISSUE THREAD

**Issue by mohanaraosv** [jborgers/sonar-pmd#290]
As PMD pmd/pmd#3366 supports Java 17, adopt the changes to be compatible.  Prepare with release candidates so that plugin changes will be ready by the time of JDK 17 release.

**Comment by sanmibuh** [comment]
Any news about Java 17 compatibility?

**Comment by sanmibuh** [comment]
Check #293 It is already working 🎉

**Comment by abryantsev** [comment]
Hi! Any new here? What is the plan to release this support?

**Comment by sanmibuh** [comment]
> Hi! Any news here? What is the plan to release this support?

Please, check #293

I think the mantainer is out 😭

**Comment by abryantsev** [comment]
> > Hi! Any news here? What is the plan to release this support?
> 
> Please, check #293
> 
> I think the mantainer is out 😭

OMG it is not merged since December 😭

**Comment by jborgers** [comment]
Fixed

**Comment by nextrevision** [comment]
Can we get a new release cut with these changes?
