### ISSUE TITLE
is sonar-pmd plugin compatible with Sonarqube EE 9.4?

### ISSUE THREAD

**Issue by shafemoh** [jborgers/sonar-pmd#337]
Hi team,
we are currently hosting Sonarqube EE 9.2.4 and we will be upgrading to Sonarqube 9.4.0. We are currently using [sonar-pmd-plugin-3.3.1.jar](https://github.com/jborgers/sonar-pmd/releases/download/3.3.1/sonar-pmd-plugin-3.3.1.jar).
Should we upgrade the sonar-pmd plugin to some higher version (if so, to which version ? )
OR Can we stay on [sonar-pmd-plugin-3.3.1.jar](https://github.com/jborgers/sonar-pmd/releases/download/3.3.1/sonar-pmd-plugin-3.3.1.jar) ?

Regards @shafemoh

**Comment by mohanaraosv** [comment]
Please find the compatibility matrix here: https://github.com/jborgers/sonar-pmd#table-of-supported-versions

**Comment by jborgers** [comment]
Tried to fix the link above, but it didn't help.

We expect that is works. But you have an old version, so we recommend to upgrade.
Please let us know your experiences.
