### ISSUE TITLE
Is custom PMD rule supported in sonarqube

### ISSUE THREAD

**Issue by Sultan1288** [jborgers/sonar-pmd#355]
HI Team,

Does custom PMD rule(Block method) is supported in sonarbuqe(Date center edition).

we have reached out to sonar vendor, they recommended to check with pmd plugin maintainer

sample code:

Mono.just('Hello World!!").block();

FYI, we have installed the PMD plugin in our sonarqube(version: 3.4.0)

**Comment by Sultan1288** [comment]
@jborgers 
Need your suggestion on this? 
Thank you in advance.

**Comment by Sultan1288** [comment]
Hello @jborgers 
could you please suggest on this, we are blocked with this?

Thanks in Advance.....

**Comment by jborgers** [comment]
Hi @Sultan1288,
It is possible but not easy. You need to translate the custom pmd rule into sonar format and package it in a plugin jar file. 
We have this currently in use in non-open source version for our customer for our jPinpoint rules and plan to make this available on Github. Not sure when however. Yet, your request increases the priority.

**Comment by jborgers** [comment]
@Sultan1288 Do you have the pmd rule available already? Use it already in your build or IDE?

**Comment by Sultan1288** [comment]
Thank you for update @jborgers 
i will check and update ASAP

**Comment by jborgers** [comment]
See https://github.com/jborgers/sonar-pmd-custom/tree/master/java-pmd6

**Comment by jborgers** [comment]
@Sultan1288 I made a release 1.0.0
