### ISSUE TITLE
Request: New plugin release with PMD 6.55

### ISSUE THREAD

**Issue by alixwar** [jborgers/sonar-pmd#414]
To get the latest false positive bug fixes (and more), I'm requesting a new release where PMD is bumped to the latest released version, 6.55: https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_release_notes.html.

I'm in particular interested in getting the fix for https://github.com/pmd/pmd/issues/3981 

Is this project still alive?

**Comment by ms-chr** [comment]
We also hope that the plugin is alive... 
At the moment, some false positives are not rewritten in java in pmd-sonar version like https://github.com/pmd/pmd/issues/2647.

**Comment by Malgosiatobiasz1** [comment]
HI, Is this plugin still maintained?

**Comment by jborgers** [comment]
Yes, it still is. You can expect more activity in the coming weeks.

**Comment by Malgosiatobiasz1** [comment]
Hi @jborgers new version od pmd plugin will be compatible with sonarqube 10.2 and 10.3 or only with 10.3 ?

**Comment by jborgers** [comment]
3.5.0 is released with PMD 6.55 support.
