### ISSUE TITLE
Make sonar-pmd up to date with PMD 6.55, support up to java20-preview, and allow java21

### ISSUE THREAD

**Issue by jborgers** [jborgers/sonar-pmd#422]
PMD 6.55 is the latest and probably the last PMD 6 release. 
PMD 7 is backwards incompatible with PMD 6, so custom rules from pmd 6 will not work in pmd 7. 
We would like to support LTS Java 21, however this is not supported by pmd 6.
Last one supported is java20-preview. It seems to cover all or at least most of the java 21 features. 
We'd like to not break Sonar on Java 21, rather warn about it and log warn when it encounters a parse exception.

**Comment by jborgers** [comment]
Release 3.5.0 is available here

**Comment by alixwar** [comment]
> Release 3.5.0 is available here

Can you please also publish this release so that it becomes available in the SonarQube Marketplace?

**Comment by jborgers** [comment]
Yes, just set things in motion at SonarQube, see:
https://community.sonarsource.com/t/new-release-sonar-pmd-plugin-3-5-0/114447
https://github.com/SonarSource/sonar-update-center-properties/pull/542
Waiting for approval by the SonarQube team...

**Comment by alixwar** [comment]
Hi, it seems that the new release is not compatible with Java 11. Could it be that this release is not in sync with the latest LTS version of SonarQube?

![image (1) (1)](https://github.com/jborgers/sonar-pmd/assets/5415786/4620d994-7942-4640-a000-67c0a4259d20)

**Comment by jborgers** [comment]
Hi Alix,

Yes, it needs Java 17.
We'll try to fix this in 3.5.1.

Op ma 6 mei 2024 om 08:41 schreef Alix ***@***.***>:

**Comment by jborgers** [comment]
3.5.0 is available in the marketplace, so closing this issue

**Comment by alixwar** [comment]
Hi, maybe this is expected but I get the following notice when analyzing using JDK 21 (I'm not sure if this is an error, warning or other):

"Requested Java version 21 ('sonar.java.source') is not supported by PMD. Using maximum supported version: 20-preview."

**Comment by jborgers** [comment]
Yes, it is expected. As far as I've tested, 20-preview is equal to 21. The scan does not break anymore, just warns and continues.
With the next major release we plan to support 21 and 22 (by using pmd-7).
