### ISSUE TITLE
Ignored rules because of PMD plugin. Assistance required

### ISSUE THREAD

**Issue by madhurilalit** [jborgers/sonar-pmd#43]
Hi Team,

We are trying to upload rule xml from one sonar instance to another. While uploading the rule to target sonar server, few rules got ignored. From sonar source, we found out they are because of 3rd party plugin. Here are the list of rules ignored.

JBA_Custom_checkstyle__com_puppycrawl_tools_checkstyle_checks_coding_IllegalTypeCheck
JBA_Custom_checkstyle__com_puppycrawl_tools_checkstyle_checks_javadoc_JavadocStyleCheck
JBA_Custom_checkstyle__com_puppycrawl_tools_checkstyle_checks_modifier_RedundantModifierCheck
JBA_Custom_checkstyle__com_puppycrawl_tools_checkstyle_checks_whitespace_EmptyLineSeparatorCheck
JBA_Custom_checkstyle__com_puppycrawl_tools_checkstyle_checks_whitespace_NoLineWrapCheck
JBA_Custom_checkstyle__com_puppycrawl_tools_checkstyle_checks_whitespace_NoWhitespaceAfterCheck
JBA_Custom_checkstyle__com_puppycrawl_tools_checkstyle_checks_whitespace_OperatorWrapCheck
JBA_Custom_checkstyle__com_puppycrawl_tools_checkstyle_checks_whitespace_NoWhitespaceBeforeCheck
JBA_Custom_checkstyle__com_puppycrawl_tools_checkstyle_checks_whitespace_ParenPadCheck
JBA_Custom_checkstyle__com_puppycrawl_tools_checkstyle_checks_whitespace_TypecastParenPadCheck
JBA_Custom_checkstyle__com_puppycrawl_tools_checkstyle_checks_whitespace_WhitespaceAfterCheck

Could you please provide me more details and how can i get them uploaded?

**Comment by jborgers** [comment]
They are not from sonar-pmd plugin, checkstyle is another one.
