### ISSUE TITLE
Release date for version 3.5.0 for PMD Plugin

### ISSUE THREAD

**Issue by fevilleg** [jborgers/sonar-pmd#453]
HI, 

We are currently upgrading our sonarqube instance and as part of our catalog of plugins we use PMD a lot, sadly, we notice that current version 3.4 is not supported by the latest version of Sonar, 

Could you please let us know when is planned to release a newer version? 
Also, in the meantime, Do you have any workaround that we can apply to force proper functionality of current PMD on Sonar v10.5? 

Thanks in advance,

**Comment by jborgers** [comment]
Hi Fernando,
Working on it. 3.5.0 hopefully this or the next week.

**Comment by jborgers** [comment]
We have a release 3.5.0!

Next steps will be deploy to maven central and publish on the sonar marketplace.

**Comment by jborgers** [comment]
It is available from maven central now

**Comment by fevilleg** [comment]
This is excellent news!!! Thanks a lot, we will get it right away and will provide feedback as well!

**Comment by jborgers** [comment]
I just set things in motion at SonarQube, see:
https://community.sonarsource.com/t/new-release-sonar-pmd-plugin-3-5-0/114447
https://github.com/SonarSource/sonar-update-center-properties/pull/542
Waiting for approval by the SonarQube team...

**Comment by jborgers** [comment]
It is released in the marketplace
