### ISSUE TITLE
Target Classfile Version changed in 3.5.0

### ISSUE THREAD

**Issue by dnl50** [jborgers/sonar-pmd#456]
Hi there,

I'm not sure if this is really an issue or an undocumented change, but the classfile version of the plugin classes changed from `52` (Java 8) to `61` (Java 11) in Release `3.5.0`. This causes our Gradle Sonar analysis to fail, since the Gradle JVM is running on Java 11.

If this change is intentional it should be mentioned in the release notes 🐰

**Comment by jborgers** [comment]
Hmm, yes, it seems to be 61 , Java 17. That will be the reason it doesn't work on Java 11.
Is this blocking for you?

**Comment by MarkusSchoelzel** [comment]
We have some projects using Java 11 Scanner, so 3.5.0 broke builds/scans for us.

If 3.5.0 is to be compatible with SonarQube 9.8, which supports scanners using Java >= 11 ([https://docs.sonarsource.com/sonarqube/9.8/requirements/prerequisites-and-overview/](https://docs.sonarsource.com/sonarqube/9.8/requirements/prerequisites-and-overview/)), it may make sense for plugins to not require a higher version.

**Comment by jborgers** [comment]
Okay. We had trouble on 11, moving to 17 solved it.
Can you work around it?

Op do 25 apr 2024 om 15:44 schreef MarkusSchoelzel ***@***.***

**Comment by dnl50** [comment]
Thanks for your fast reply. We downgraded the plugin back to Version `3.4.0` and everything works again.

**Comment by jborgers** [comment]
okay, great.
