### ISSUE TITLE
Release 3.5.0 not compatible with SonarQube 9.9 LTS analysis on Java 11: "The plugin [pmd] does not support Java 11"

### ISSUE THREAD

**Issue by alixwar** [jborgers/sonar-pmd#464]
Projects that use JDK 11 in their build pipelines get this error:

![image (1) (1)](https://github.com/jborgers/sonar-pmd/assets/5415786/f6a3c4b0-2ee5-421b-8c55-f1a302e21272)

So it seems that release 3.5 has been targetting a newer SonarQube version and not 9.9 LTS

**Comment by jborgers** [comment]
"The SonarQube server now requires Java 17. Analysis may continue to use Java 11 if necessary. ([SONAR-17566 90](https://sonarsource.atlassian.net/browse/SONAR-17566))."
Release 3.5.0 only supports Java 17 for the analysis.

We hope to support Java 11 again for analysis in upcoming release 3.5.1.

**Comment by jborgers** [comment]
3.5.1-beta pre-release is published to try-out.

**Comment by jborgers** [comment]
We just released 3.5.1

**Comment by alixwar** [comment]
> Nothing heard, assuming it works for @alixwar

I'm still waiting for our operations team to install the upgrade, but it will likely work. Thanks :)

**Comment by dvbeek** [comment]
We have tested this, and can confirm version 3.5.1 works perfectly with Java 11 and Java 17 👍
